//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.WebAtividadeEntrevista.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FI.WebAtividadeEntrevista.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiario alterado com sucesso..
        /// </summary>
        public static string BeneficiarioController_BeneficiarioAlterado {
            get {
                return ResourceManager.GetString("BeneficiarioController_BeneficiarioAlterado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiario cadastrado com sucesso..
        /// </summary>
        public static string BeneficiarioController_BeneficiarioCadastrado {
            get {
                return ResourceManager.GetString("BeneficiarioController_BeneficiarioCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiário removido com sucesso..
        /// </summary>
        public static string BeneficiarioController_BeneficiarioRemovido {
            get {
                return ResourceManager.GetString("BeneficiarioController_BeneficiarioRemovido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string BeneficiarioController_Erro {
            get {
                return ResourceManager.GetString("BeneficiarioController_Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Id do beneficiário não foi informado ou é inválido..
        /// </summary>
        public static string BeneficiarioController_Erro_IdInvalido {
            get {
                return ResourceManager.GetString("BeneficiarioController_Erro_IdInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiário não encontrado..
        /// </summary>
        public static string BeneficiarioController_Erro_NaoEncontrado {
            get {
                return ResourceManager.GetString("BeneficiarioController_Erro_NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar.
        /// </summary>
        public static string FormBeneficiarios_BotaoAlterar {
            get {
                return ResourceManager.GetString("FormBeneficiarios_BotaoAlterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar.
        /// </summary>
        public static string FormBeneficiarios_BotaoCadastrar {
            get {
                return ResourceManager.GetString("FormBeneficiarios_BotaoCadastrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string FormBeneficiarios_BotaoExcluir {
            get {
                return ResourceManager.GetString("FormBeneficiarios_BotaoExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string FormBeneficiarios_BotaoSalvar {
            get {
                return ResourceManager.GetString("FormBeneficiarios_BotaoSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string FormBeneficiarios_Cancelar {
            get {
                return ResourceManager.GetString("FormBeneficiarios_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string FormBeneficiarios_CPF {
            get {
                return ResourceManager.GetString("FormBeneficiarios_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex: 000.000.000-00.
        /// </summary>
        public static string FormBeneficiarios_CPF_Placeholder {
            get {
                return ResourceManager.GetString("FormBeneficiarios_CPF_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro desconhecido. Verifique a sua conexão com a Internet e tente novamente..
        /// </summary>
        public static string FormBeneficiarios_Erro_ErroDesconhecido {
            get {
                return ResourceManager.GetString("FormBeneficiarios_Erro_ErroDesconhecido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro interno no servidor..
        /// </summary>
        public static string FormBeneficiarios_Erro_ErroInterno {
            get {
                return ResourceManager.GetString("FormBeneficiarios_Erro_ErroInterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro.
        /// </summary>
        public static string FormBeneficiarios_Erro_TituloModal {
            get {
                return ResourceManager.GetString("FormBeneficiarios_Erro_TituloModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        public static string FormBeneficiarios_Fechar {
            get {
                return ResourceManager.GetString("FormBeneficiarios_Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar.
        /// </summary>
        public static string FormBeneficiarios_Limpar {
            get {
                return ResourceManager.GetString("FormBeneficiarios_Limpar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string FormBeneficiarios_Nome {
            get {
                return ResourceManager.GetString("FormBeneficiarios_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex: João Silva.
        /// </summary>
        public static string FormBeneficiarios_Nome_Placeholder {
            get {
                return ResourceManager.GetString("FormBeneficiarios_Nome_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação concluída com sucesso..
        /// </summary>
        public static string FormBeneficiarios_RequisicaoSucesso {
            get {
                return ResourceManager.GetString("FormBeneficiarios_RequisicaoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar.
        /// </summary>
        public static string FormBeneficiarios_Salvar {
            get {
                return ResourceManager.GetString("FormBeneficiarios_Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiarios.
        /// </summary>
        public static string FormBeneficiarios_Titulo {
            get {
                return ResourceManager.GetString("FormBeneficiarios_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiários cadastrados para o cliente.
        /// </summary>
        public static string FormBeneficiarios_TituloGrid {
            get {
                return ResourceManager.GetString("FormBeneficiarios_TituloGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o CPF.
        /// </summary>
        public static string ValidarCPF_CampoObrigatorio {
            get {
                return ResourceManager.GetString("ValidarCPF_CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF informado é inválido. Verifique o CPF digitado e tente novamente..
        /// </summary>
        public static string ValidarCPF_DigitoInvalido {
            get {
                return ResourceManager.GetString("ValidarCPF_DigitoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o CPF no formato 000.000.000-00 e tente novamente..
        /// </summary>
        public static string ValidarCPF_FormatoInvalido {
            get {
                return ResourceManager.GetString("ValidarCPF_FormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF já se encontra cadastrado. Não é possível utilizar este CPF novamente..
        /// </summary>
        public static string ValidarCPF_JaExisteNaBase {
            get {
                return ResourceManager.GetString("ValidarCPF_JaExisteNaBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo do campo de CPF é de 14 caracteres (000.000.000-00)..
        /// </summary>
        public static string ValidarCPF_TamanhoMaximo {
            get {
                return ResourceManager.GetString("ValidarCPF_TamanhoMaximo", resourceCulture);
            }
        }
    }
}
