CREATE PROCEDURE FI_SP_VerificaBeneficiario
	@CPF		VARCHAR(14),
	@ID			BIGINT = NULL,
	@IDCLIENTE	BIGINT = NULL
AS
BEGIN
	SET NOCOUNT OFF;

	DECLARE @SCRIPT NVARCHAR(MAX);
	DECLARE @CAMPOS NVARCHAR(MAX)

	SET @SCRIPT = 'SELECT 1 FROM BENEFICIARIOS WITH(NOLOCK) WHERE CPF = @CPF';
	SET @CAMPOS = '@CPF VARCHAR(14)';

	IF (ISNULL(@ID, 0) > 0)
	BEGIN
		SET @SCRIPT =  @SCRIPT + ' AND ID <> ' + CONVERT(NVARCHAR(30), @ID);
	END

	IF (ISNULL(@IDCLIENTE, 0) > 0)
	BEGIN
		SET @SCRIPT =  @SCRIPT + ' AND IDCLIENTE = ' + CONVERT(NVARCHAR(30), @IDCLIENTE);
	END

	EXECUTE SP_EXECUTESQL @SCRIPT, @CAMPOS, @CPF;
END