CREATE PROCEDURE FI_SP_ConsBeneficiario
	@ID			BIGINT = NULL,
	@IDCLIENTE	BIGINT = NULL
AS
BEGIN
	SELECT 
		* 
	FROM 
		BENEFICIARIOS WITH(NOLOCK) 
	WHERE 
		ID = ISNULL(NULLIF(@ID, 0), ID) 
		AND IDCLIENTE = ISNULL(NULLIF(@IDCLIENTE, 0), IDCLIENTE)
	;

	/*
	IF (@ID > 0)
	BEGIN
		SELECT * FROM BENEFICIARIOS WITH(NOLOCK) WHERE ID = @ID;
	END
	ELSE IF (@IDCLIENTE > 0)
	BEGIN
		SELECT * FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @IDCLIENTE;
	END
	ELSE
	BEGIN
		SELECT * FROM BENEFICIARIOS WITH(NOLOCK);
	END
	*/
END
