CREATE PROC FI_SP_VerificaCliente
	@CPF	VARCHAR(14),
	@ID		BIGINT = 0
AS
BEGIN
	SET NOCOUNT OFF;

	DECLARE @SCRIPT NVARCHAR(MAX);
	DECLARE @CAMPOS NVARCHAR(MAX)

	SET @SCRIPT = 'SELECT 1 FROM CLIENTES WITH(NOLOCK) WHERE CPF = @CPF';
	SET @CAMPOS = '@CPF VARCHAR(14)';

	IF (@ID > 0)
	BEGIN
		SET @SCRIPT =  @SCRIPT + ' AND ID <> ' + CONVERT(NVARCHAR(30), @ID);
	END

	EXECUTE SP_EXECUTESQL @SCRIPT, @CAMPOS, @CPF;
END